apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitdocs
spec:
  template:
    spec:
      containers:
      - name: git-sync
        volumeMounts:
        - name: ssh-key-volume
          mountPath: "/etc/git-secret"
        env:
        - name: GIT_SYNC_REPO
          value: "git@bitbucket.org:jimangel/jimangel.io.git"
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_KNOWN_HOSTS
          value: "false"
      volumes:
      - name: ssh-key-volume
        secret:
          secretName: git-docs-ssh-key
          defaultMode: 0400