apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitdocs
spec:
  template:
    spec:
      containers:
      - name: git-sync
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/kubernetes-sigs/kind.git
      - name: hugo
        args: ["while [ ! $(ls /src/git-sync/site/config*) ]; do echo 'No Config' && sleep 1; done && hugo --watch --source=/src/git-sync/site --cleanDestinationDir"]